server.address=0.0.0.0
server.port=8081
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.application.name=helpdesk
spring.datasource.url=jdbc:mysql://localhost:3306/GP_2025
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto = update

jwt.secret=P15CB/CHFxH68kCnvOKx8I8WWpVIyS6ozQE8np8H1b5Vp2r2uZvT94JDhy0YK1IpJapL5tFc0CwYw2aeSZfliA==

#configuiration Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dahman.ormvad@gmail.com
spring.mail.password=hssj jsim tyvm srgd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true